#!/bin/tcsh

viskom

set lockfile = ~/viskomcatscience_01-lock

if ! -e $lockfile then
 touch $lockfile
 echo =================
 echo cronjobcatscience_01 started at `date`
 echo SORTDATA
 foreach yyyymm (`cat $scr/yyyymm`)
  sortdata $yyyymm
 end
 science
 echo DETECTALL SCIENCE
 source $scr/detectall_xx 01 | grep -v present
 echo ===== Finished science01 at `date`
 \rm $lockfile
else
 echo ====== lock File found - not started at `date`
endif
