#!/bin/tcsh

viskom

#if `ps aux | grep md0_res | grep "\[" |wc -l` then
# echo ===XXXXXXX=== md0_resync in progress. Not starting at `date` ===
# exit
#endif

set lockfile = ~/viskompsf-lock

if ! -e $lockfile then
 touch $lockfile
 echo =================
 echo cronjobpsf started at `date`
 science
 psfsummaries `cat $scr/yyyymm`
 \rm $lockfile
 echo ===== Finished at `date` 
else
 echo ===== lock File found - not started at `date`
endif

